MCU = RP2040
BOOTLOADER = rp2040

# SRC = keyboard.c

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
NKRO_ENABLE = yes
COMBO_ENABLE = yes
# COMBO_ENABLE = yes
STENO_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = vendor
